### ISSUE TITLE
Captcha kann nicht gelöst werden

### ISSUE THREAD

**Issue by sallandcall** [implod3/Burning-Series-Downloader#6]
Traceback (most recent call last):
  File ".\starter.py", line 5, in <module>
    c.get_serie()
  File "C:\Users\b\Downloads\Burning-Series-Downloader-master\Burning-Series-Downloader-master\main.py", line 40, in get_serie
    self.download()
  File "C:\Users\b\Downloads\Burning-Series-Downloader-master\Burning-Series-Downloader-master\main.py", line 77, in download
    d.download()
  File "C:\Users\b\Downloads\Burning-Series-Downloader-master\Burning-Series-Downloader-master\download.py", line 65, in download
    self.download_from_src(self.get_site(self.links[self.session]))
  File "C:\Users\b\Downloads\Burning-Series-Downloader-master\Burning-Series-Downloader-master\download.py", line 145, in get_site
    stop = s.solve_recaptcha(self.browser)
  File "C:\Users\b\Downloads\Burning-Series-Downloader-master\Burning-Series-Downloader-master\recaptcha.py", line 47, in solve_recaptcha
    self.browser.switch_to.frame(self.browser.find_elements_by_tag_name("iframe")[5])
IndexError: list index out of range

**Comment by implod3** [comment]
Thank you for your report. This is a known problem and will be solved in the course of next week!
